---
- name: Environment Variables file
  become: yes
  template:
    src: defaults_trytond.j2
    dest: "/etc/default/trytond"
    mode: 0640
  vars:
    OTRS_SALT: "{{ otrs_salt }}"
    OTRS_RPC_url: "{{ otrs_rpc_url }}"
    OTRS_RPC_user: "{{ otrs_rpc_user }}"
    OTRS_RPC_passw: "{{ otrs_rpc_passw }}"
    TRYTON_DATABASE: "{{ celery_tryton_database }}"
    TRYTON_CONFIG: "{{ celery_tryton_config }}"

- name: Create Systemd service
  become: yes
  template:
    src: trytond.service.j2
    dest: "/etc/systemd/system/trytond@.service"
    mode: 0640
  vars:
    virtualenv_path: "{{ venv_path }}"
    eticom_path: "{{ tryton_path }}"

- name: Create Cron Systemd service
  become: yes
  template:
    src: trytond-cron.service.j2
    dest: "/etc/systemd/system/trytond-cron.service"
    mode: 0640
  vars:
    virtualenv_path: "{{ venv_path }}"
    eticom_path: "{{ tryton_path }}"

- name: Create Celery-Tryton Systemd service
  become: yes
  template:
    src: trytond-celery.service.j2
    dest: "/etc/systemd/system/trytond-celery.service"
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"
    mode: 0640
  vars:
    virtualenv_path: "{{ venv_path }}"
    eticom_path: "{{ tryton_path }}"

- name: Enable Systemd service
  become: yes
  systemd:
    name: "{{ item }}.service"
    enabled: yes
    state: restarted
    daemon_reload: yes
  with_items:
    - "trytond-celery"
    - "trytond-cron"
    - "trytond@trytond1"
    - "trytond@trytond2"
    - "trytond@trytond3"
    - "trytond@trytond4"

- name: Copy sudoers configuration for Tryton  administrators
  become: yes
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/90-tryton-admins"
    mode: 0440
