---
- name: Add the Postgres repository
  become: yes
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64
    state: present

- name: Install system required packages
  become: yes
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - git=1:2.11.0-3+deb9u4
    - mercurial=4.0-1+deb9u1
    - quilt=0.63-8
    - python-pip=9.0.1-2
    - python-dev=2.7.13-2
    - libxml2=2.9.4+dfsg1-2.2+deb9u2
    - libxml2-dev=2.9.4+dfsg1-2.2+deb9u2
    - libxslt1-dev=1.1.29-2.1
    - build-essential=12.3
    - enchant=1.6.0-11+b1
    - libffi-dev=3.2.1-6
    - libssl-dev=1.1.0f-3+deb9u2
    - libldap2-dev=2.4.44+dfsg-5+deb9u2
    - libsasl2-dev=2.1.27~101-g0780600+dfsg-3
    - unoconv=0.7-1.1
    - libdwarf-dev=20161124-1+deb9u1
    - libelf-dev=0.168-1
    - libunwind-dev=1.1-4.1
    - ghostscript=9.25~dfsg-0+deb9u1
    - libssl-dev=1.1.0f-3+deb9u2
    - libffi-dev=3.2.1-6
#    - libpq5=11.1-1.pgdg90+1
#    - libpq-dev=11.1-1.pgdg90+1

#    - rabbitmq-server=3.6.6-1
#    - nginx=1.10.3-1+deb9u2
