# from galaxy
- src: coopdevs.sys-admins-role
  version: v0.0.1

- src: geerlingguy.postgresql
  version: 2.0.1

- src: lciolecki.virtualenvwrapper
  version: v1.1.0

- src: geerlingguy.nodejs
  version: 4.2.2

- src: weareinteractive.vsftpd
  version: 1.5.1

- src: coopdevs.certbot_nginx
  version: 0.0.4
