---
- name: Clone Tryton repository
  hg:
    repo: '{{ item.url }}'
    dest: '{{ item.path }}'
    revision: '{{ item.revision }}'
  with_items: '{{ tryton_repositories }}'

- name: Set permissions for the Tryton folder and subfolders
  file:
    dest: '{{ item.path }}'
    owner: '{{ tryton_user }}'
    group: '{{ tryton_user }}'
    mode: 0755
    recurse: yes
  with_items: '{{ tryton_repositories }}'

- name: Install Tryton dependencies
  become: yes
  become: '{{ tryton_user }}'
  pip:
    requirements: '{{ item.path }}/requirements.txt'
    virtualenv: '{{ venv_path }}'
  with_items: '{{ tryton_repositories }}'
