---
- name: Install RabbitMQ
  become: yes
  apt:
    pkg: 'rabbitmq-server=3.6.6-1'
    state: present
    update_cache: yes

- name: Enables the rabbitmq_management plugin
  become: yes
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  ignore_errors: yes

- name: Create RabbitMQ VHost
  become: yes
  rabbitmq_vhost:
    name: "{{ celery_vhost }}"
    state: present
  ignore_errors: yes

- name: Create RabbitMQ User
  become: yes
  rabbitmq_user:
    user: "{{ celery_user }}"
    password: "{{ celery_password }}"
    tags: administrator
    state: present
    permissions:
      - vhost: "{{ celery_vhost }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
  ignore_errors: yes
