---
# Create directories
- name: Create trytond directory in /etc/
  become: yes
  file:
    path: /etc/trytond/
    state: directory
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"
    mode: 02700

- name: Create /var/log/eticom directory
  become: yes
  file:
    path: /var/log/eticom/
    state: directory
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"
    mode: 02700

- name: Create /var/run/trytond directory
  become: yes
  file:
    path: /var/run/trytond/
    state: directory
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"
    mode: 02755

# Create files
- name: Copy trytond configuration file to /etc/trytond/
  become: yes
  template:
    src: trytond.conf.j2
    dest: "/etc/trytond/{{ file_name }}"
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"
    mode: 0640
  vars:
    file_name: "{{ item.file_name }}"
    listen_port: "{{ item.listen_port }}"
    db_uri: "{{ item.db_uri }}"
    pidfile: "{{ item.pidfile }}"
    logconf: "{{ item.logconf }}"
    super_pwd: "{{ item.super_pwd }}"
    cron: "{{ item.cron }}"
    smtp_max_connections: "{{ item.smtp_max_connections }}"
    verbose: "{{ item.verbose }}"
    dev: "{{ tryton_dev }}"
  with_items: "{{ configuration_files }}"

- name: Copy trytond log configuration file to /etc/trytond/
  become: yes
  template:
    src: trytond.logconf.j2
    dest: "/etc/trytond/{{ file_name }}"
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"
    mode: 0640
  vars:
    file_name: "{{ item.file_name }}"
    log_path: "{{ item.log_path }}"
    logger_level: "{{ item.logger_level }}"
    handler_level: "{{ item.handler_level }}"
  with_items: "{{ log_configuration_files }}"
