---
- name: Environment Variables file
  become: yes
  template:
    src: defaults_trytond.j2
    dest: "{{ tryton_defaults }}"
    owner: "{{ tryton_user }}"
    mode: 0640
  vars:
    tryton_database: "{{ db_name }}"
  tags: defaults

- name: Create Systemd service
  become: yes
  template:
    src: trytond.service.j2
    dest: "/etc/systemd/system/trytond@.service"
    mode: 0640
  vars:
    virtualenv_path: "{{ venv_path }}"
    eticom_path: "{{ tryton_path }}"

- name: Create Cron Systemd service
  become: yes
  template:
    src: trytond-cron.service.j2
    dest: "/etc/systemd/system/trytond-cron.service"
    mode: 0640
  vars:
    virtualenv_path: "{{ venv_path }}"
    eticom_path: "{{ tryton_path }}"

# TODO: This unit not works because the PYTHONPATH is not correctly set
# - name: Create UWSGI Systemd service
#   become: yes
#   template:
#     src: trytond-uwsgi.service.j2
#     dest: "/etc/systemd/system/trytond-uwsgi.service"
#     mode: 0640

- name: Create Celery-Tryton Eticom Systemd service
  become: yes
  template:
    src: eticom-celery.service.j2
    dest: "/etc/systemd/system/eticom-celery.service"
    mode: 0640
  vars:
    virtualenv_path: "{{ venv_path }}"
    eticom_path: "{{ tryton_path }}"

- name: Create Celery-Tryton OpenCell Systemd service
  become: yes
  template:
    src: opencell-celery.service.j2
    dest: "/etc/systemd/system/opencell-celery.service"
    mode: 0640
  vars:
    virtualenv_path: "{{ venv_path }}"
    eticom_path: "{{ tryton_path }}"

- name: Create Flower Systemd service
  become: yes
  template:
    src: flower.service.j2
    dest: "/etc/systemd/system/flower.service"
    mode: 0640
  vars:
    virtualenv_path: "{{ venv_path }}"

- name: Enable Systemd service
  become: yes
  systemd:
    name: "{{ item }}.service"
    enabled: yes
    state: restarted
    daemon_reload: yes
  with_items:
    - "trytond-cron"
    - "eticom-celery"
    - "opencell-celery"
    - "flower"
  # - "trytond-uwsgi"
    - "trytond@eticom1"
    - "trytond@eticom2"
    - "trytond@eticom3"
    - "trytond@eticom4"

- name: Copy sudoers configuration for Tryton  administrators
  become: yes
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/90-tryton-admins"
    mode: 0440

- name: Create script to restart all Tryton
  become: yes
  become_user: "{{ tryton_user }}"
  copy:
    src: restart_all.sh
    dest: "/home/{{ tryton_user }}/restart_all"
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"
    mode: 0740

