---
# Sysadmins
system_administrators_group: "sysadmins"
system_administrators:
  - name: tryton
    ssh_key: "~/.ssh/id_rsa.pub"
    state: present

# Tryton users
tryton_user: "tryton"
tryton_users:
  - name: daniel
    ssh_key: "~/.ssh/id_rsa.pub"
    state: present

# Tryton vars
venv_path: "/home/tryton/.virtualenvs/tryton"
tryton_user: "tryton"
tryton_path: "/opt/eticom"

# Postgresql vars
database_name: "tryton"

# Tryton Configuration files
configuration_files:
  - file_name: "trytond.conf"
    listen_port: "8000"
    db_uri: "postgresql:///tryton"
    db_copy: "/opt/eticom/backups"
    pidfile: "/var/run/trytond/trytond.pid"
    logconf: "/etc/trytond/trytond.logconf"
    super_pwd: ""
    cron: "True"
    smtp_max_connections: 4
    dev: "True"
    verbose: "True"
  - file_name: "trytond1.conf"
    listen_port: "8001"
    db_uri: "postgresql:///tryton"
    db_copy: "/opt/eticom/backups"
    pidfile: "/var/run/trytond/trytond1.pid"
    logconf: "/etc/trytond/trytond1.logconf"
    super_pwd: ""
    cron: "False"
    smtp_max_connections: 4
    dev: "True"
    verbose: "True"
  - file_name: "trytond2.conf"
    listen_port: "8002"
    db_uri: "postgresql:///tryton"
    db_copy: "/opt/eticom/backups"
    pidfile: "/var/run/trytond/trytond2.pid"
    logconf: "/etc/trytond/trytond2.logconf"
    super_pwd: ""
    cron: "False"
    smtp_max_connections: 4
    dev: "True"
    verbose: "True"
  - file_name: "trytond3.conf"
    listen_port: "8003"
    db_uri: "postgresql:///tryton"
    db_copy: "/opt/eticom/backups"
    pidfile: "/var/run/trytond/trytond3.pid"
    logconf: "/etc/trytond/trytond3.logconf"
    super_pwd: ""
    cron: "False"
    smtp_max_connections: 4
    dev: "True"
    verbose: "True"
  - file_name: "trytond4.conf"
    listen_port: "8004"
    db_uri: "postgresql:///tryton"
    db_copy: "/opt/eticom/backups"
    pidfile: "/var/run/trytond/trytond4.pid"
    logconf: "/etc/trytond/trytond4.logconf"
    super_pwd: ""
    cron: "False"
    smtp_max_connections: 4
    dev: "True"
    verbose: "True"

# Log Tryton Configuration files
log_configuration_files:
  - file_name: "trytond.logconf"
    log_path: "/var/log/trytond/trytond.log"
    logger_level: "INFO"
    handler_level: "INFO"
  - file_name: "trytond1.logconf"
    log_path: "/var/log/trytond/trytond1.log"
    logger_level: "INFO"
    handler_level: "INFO"
  - file_name: "trytond2.logconf"
    log_path: "/var/log/trytond/trytond2.log"
    logger_level: "INFO"
    handler_level: "INFO"
  - file_name: "trytond3.logconf"
    log_path: "/var/log/trytond/trytond3.log"
    logger_level: "INFO"
    handler_level: "INFO"
  - file_name: "trytond4.logconf"
    log_path: "/var/log/trytond/trytond4.log"
    logger_level: "INFO"
    handler_level: "INFO"

# Tryton Environment Variables
otrs_salt: "1234"
otrs_rpc_url: "www.test.coop"
otrs_rpc_user: "rpc_user"
otrs_rpc_passw: "rpc_passw"
