---
# Sysadmins
system_administrators_group: sysadmins
system_administrators:
  - name: admin
    ssh_key: '~/.ssh/id_rsa.pub'
    state: present

# Tryton users
tryton_user: tryton
# Users with access to Tryton user via SSH. The name ins only for document who the key is.
tryton_users:
  - name: daniel
    ssh_key: '~/.ssh/id_rsa.pub'
    state: present

# Virtualenv vars
venv_name: trytond
venv_path: "/home/{{ tryton_user }}/.virtualenvs/{{ venv_name }}"

# Tryton vars
tryton_path: "/home/{{ tryton_user }}/trytond"
# You can clone more that one Tryton repository using Mercurial
tryton_repositories:
  - url: 'https://hg.tryton.org/trytond'
    path: "/home/{{ tryton_user }}/trytond"
    revision: default

# OTRS vars
otrs_salt: 1234
otrs_rpc_url: 'www.test.coop'
otrs_rpc_user: rpc_user
otrs_rpc_passw: rpc_passw

# Postgresql vars
db_name: tryton
db_user: tryton
db_user_password: 1234
db_port: 5432
db_locales: 'ca_ES.UTF-8'
db_options:
  - option: lc_messages
    value: "{{ db_locales }}"
  - option: lc_monetary
    value: "{{ db_locales }}"
  - option: lc_numeric
    value: "{{ db_locales }}"
  - option: lc_time
    value: "{{ db_locales }}"
db_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }

# Tryton Configuration files
configuration_files:
  - file_name: 'trytond.conf'
    listen_port: 8000
    db_uri: 'postgresql:///tryton'
    db_copy: '/opt/eticom/backups'
    pidfile: '/var/run/trytond/trytond.pid'
    logconf: '/etc/trytond/trytond.logconf'
    super_pwd: ''
    cron: 'True'
    smtp_max_connections: 4
    dev: 'True'
    verbose: 'True'
  - file_name: 'trytond1.conf'
    listen_port: 8001
    db_uri: 'postgresql:///tryton'
    db_copy: '/opt/eticom/backups'
    pidfile: '/var/run/trytond/trytond1.pid'
    logconf: '/etc/trytond/trytond1.logconf'
    super_pwd: ''
    cron: 'False'
    smtp_max_connections: 4
    dev: 'True'
    verbose: 'True'

# Log Tryton Configuration files
log_configuration_files:
  - file_name: 'trytond.logconf'
    log_path: '/var/log/trytond/trytond.log'
    logger_level: INFO
    handler_level: INFO
  - file_name: 'trytond1.logconf'
    log_path: '/var/log/trytond/trytond1.log'
    logger_level: INFO
    handler_level: INFO
