---
- name: Create tryton group to manage the application
  become: yes
  group:
    name: "tryton"
    state: "present"

- name: Create app user to run the application
  become: yes
  user:
    name: "{{ tryton_user }}"
    state: "present"
    shell: "/bin/bash"
    groups: "tryton"

- name: Add SSH public keys to app user
  become: yes
  authorized_key:
    user: "{{ tryton_user }}"
    key: "{{ lookup('file', item.ssh_key) }}"
    state: "{{ item.state }}"
  when: item.state == "present"
  with_items: "{{ tryton_user_keys }}"
