---
- name: Create script to run web
  become: yes
  template:
    src: up-web.j2
    dest: "/home/{{ tryton_user }}/up-web"
    mode: 0740
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"

- name: Create script to run Tryton
  become: yes
  template:
    src: up.j2
    dest: "/home/{{ tryton_user }}/up"
    mode: 0740
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"

- name: Create script to update Tryton
  become: yes
  template:
    src: update.j2
    dest: "/home/{{ tryton_user }}/update"
    mode: 0740
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"

- name: Create script to prepare Production dump
  become: yes
  template:
    src: prepare-prod-db.j2
    dest: "/home/{{ tryton_user }}/prepare-prod-db"
    mode: 0740
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"

- name: Remove NGINX default server
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create Forms NGINX configuration link
  become: yes
  template:
    src: eticom.nginx.j2
    dest: /etc/nginx/sites-available/eticom
    mode: 0755
    owner: root
    group: root

- name: Enable the NGINX configuration
  become: yes
  file:
    src: /etc/nginx/sites-available/eticom
    dest: /etc/nginx/sites-enabled/eticom
    state: link

- name: Restart NGINX
  become: yes
  systemd:
    name: nginx
    state: started
