---
# Create directories
- name: Copy price.js
  become_user: "{{ tryton_user }}"
  copy:
    src: prices.js
    dest: "{{ galatea_path}}/static/prices.js"
    owner: "{{ tryton_user }}"
    group: "{{ tryton_user }}"

- name: Create script to run web
  become_user: "{{ tryton_user }}"
  template:
    src: up-web.j2
    dest: "/home/{{ tryton_user }}/up-web"
    mode: 0740

- name: Create script to run Tryton
  become_user: "{{ tryton_user }}"
  template:
    src: up.j2
    dest: "/home/{{ tryton_user }}/up"
    mode: 0740

- name: Create script to update Tryton
  become_user: "{{ tryton_user }}"
  template:
    src: update.j2
    dest: "/home/{{ tryton_user }}/update"
    mode: 0740

- name: Remove NGINX default server
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create NGINX configuration link
  become: yes
  file:
    src: '{{ galatea_path }}/{{ nginx_config }}'
    dest: /etc/nginx/sites-available/eticom
    state: link

- name: Enable the NGINX configuration
  become: yes
  file:
    src: /etc/nginx/sites-available/eticom
    dest: /etc/nginx/sites-enabled/eticom
    state: link

- name: Restart NGINX
  become: yes
  systemd:
    name: nginx
    state: started
