---
# Install some Python development tools
dev_mode: true

# Set Tryton in development mode
tryton_dev: True

# Sysadmins
system_administrators:
  - name: daniel
    ssh_key: '{{ inventory_dir }}/../file/keys/daniel.pub'
    state: present
  - name: enrico
    ssh_key: '{{ inventory_dir }}/../file/keys/enrico.pub'
    state: present
  - name: ferran
    ssh_key: '{{ inventory_dir }}/../file/keys/ferran.pub'
    state: present

# Users with access to Tryton user via SSH. The name ins only for document who the key is.
tryton_user_keys:
  - ssh_key: '~/.ssh/id_rsa.pub'
    state: present

trytond_db_uri: 'postgresql:///{{ db_name }}'
uwsgi_config: 'server-eticom-dev.ini'
nginx_config: 'uwsgi-dev.nginx'

# Integrations

## OTRS
otrs_url: 'https://stagingotrs.somconnexio.coop:10443/'
otrs_rpc_url: 'https://stagingotrs.somconnexio.coop:10443/rpc.pl'

# OpenCell
opencell_url: 'https://opencell-test.coopdevs.org/opencell'
