---
# Install some Python development tools
dev_mode: true

# Set Tryton in development mode
tryton_dev: True

# Users with access to Tryton user via SSH. The name ins only for document who the key is.
tryton_user_keys:
  - ssh_key: '{{ inventory_dir }}/../file/keys/daniel.pub'
    state: present
  - ssh_key: '{{ inventory_dir }}/../file/keys/enrico.pub'
    state: present
  - ssh_key: '{{ inventory_dir }}/../file/keys/pau.pub'
    state: present
  - ssh_key: '{{ inventory_dir }}/../file/keys/ferran.pub'
    state: present

trytond_db_uri: 'postgresql://{{ db_user }}:{{ db_user_password }}@localhost:{{ db_port }}/{{ db_name }}'
uwsgi_config: 'server-eticom-staging.ini'
nginx_config: 'uwsgi-dev.nginx'

# Let's Encrypt conf
certificate_authority_email: "info@coopdevs.org"
development_environment: false
