---
system_administrators:
  - name: daniel
    ssh_key: '{{ inventory_dir }}/../file/keys/daniel.pub'
    state: present
  - name: enrico
    ssh_key: '{{ inventory_dir }}/../file/keys/enrico.pub'
    state: present
  - name: pau
    ssh_key: '{{ inventory_dir }}/../file/keys/pau.pub'
    state: present
  - name: gerard
    ssh_key: '{{ inventory_dir }}/../file/keys/gerard.pub'
    state: present
