---
# TODO
# We have a problem with the database creation. We replicate the logic of https://github.com/coopdevs/timeoverflow-provisioning/blob/master/roles/database/tasks/main.yml but it's not working...
# TASK [geerlingguy.postgresql : Ensure PostgreSQL databases are present.] *********************************************
# An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ProgrammingError: role "eticom" does not exist
# failed: [local.somconnexio.coop] (item={u'owner': u'eticom', u'lc_collate': u'ca_ES.UTF-8', u'port': 5432, u'name': u'eticom', u'lc_ctype': u'ca_ES.UTF-8'}) => {"changed": false, "item": {"lc_collate": "ca_ES.UTF-8", "lc_ctype": "ca_ES.UTF-8", "name": "eticom", "owner": "eticom", "port": 5432}, "msg": "Database query failed: role \"eticom\" does not exist\n"}

- import_role:
    name: geerlingguy.postgresql
  become: yes
  vars:
    postgresql_locales:
      - '{{ db_locales }}'
    postgresql_global_config_options: '{{ db_options }}'
    postgresql_hba_entries: '{{ db_hba_entries }}'

- include_role:
    name: geerlingguy.postgresql
    tasks_from: users
  become: yes
  vars:
    postgresql_users:
      - name: '{{ db_user }}'
        password: '{{ db_user_password }}'
        role_attr_flags: CREATEDB
        port: '{{ db_port }}'
      - name: '{{ tryton_user }}'
        role_attr_flags: SUPERUSER
        port: '{{ db_port }}'

- include_role:
    name: geerlingguy.postgresql
    tasks_from: databases
  become: yes
  vars:
    postgresql_databases:
      - name: '{{ db_name }}'
        lc_collate: '{{ db_locales }}'
        lc_ctype: '{{ db_locales }}'
        owner: '{{ db_user }}'
        port: '{{ db_port }}'
