---
- name:  Provision FTP Server
  hosts: tryton
  roles:
    - role: weareinteractive.vsftpd
      become: yes
      vars:
        vsftpd_users:
           - username: "{{ ftp_user }}"
             name: FTP User
             password: "{{ ftp_password }}"
        vsftpd_config:
          listen_port: 990
          local_enable: YES
          write_enable: YES
          chroot_local_user: YES
          xferlog_enable: YES
          log_ftp_protocol: YES
          allow_writeable_chroot: YES
