---
- name:  Provision a machine to run Tryton server
  hosts: tryton
  roles:
    - role: users
      tags: users

    - role: system_packages
      tags: system

    - role: geerlingguy.postgresql
      become: yes
      vars:
        postgresql_locales:
          - '{{ db_locales }}'
        postgresql_global_config_options: '{{ db_options }}'
        postgresql_hba_entries: '{{ db_hba_entries }}'
        postgresql_users:
          - name: '{{ db_user }}'
            password: '{{ db_user_password }}'
            role_attr_flags: CREATEDB
            port: '{{ db_port }}'
          - name: '{{ otrs_db_user }}'
            password: '{{ otrs_db_password }}'
            priv: party_otrs_view:SELECT/otrs_contract:SELECT
            db: '{{ db_name }}'
            port: '{{ db_port }}'
          - name: '{{ tryton_user }}'
            role_attr_flags: SUPERUSER
            port: '{{ db_port }}'
        postgresql_databases:
          - name: '{{ db_name }}'
            lc_collate: '{{ db_locales }}'
            lc_ctype: '{{ db_locales }}'
            owner: '{{ db_user }}'
            port: '{{ db_port }}'
      tags: database

    - role: virtualenv
      tags: virtualenv

    - role: geerlingguy.nodejs
      tags: npm
      become: yes
      vars:
        nodejs_version: "8.x"
        nodejs_install_npm_user: "{{ tryton_user }}"
        nodejs_npm_global_packages:
          # Install a specific version of a package.
          - name: bower
            version: 1.8.8
          - name: grunt
            version: "^1.0.4"
          - name: grunt-contrib-concat
            version: "~0.5.1"
          - name: grunt-contrib-cssmin
            version: "^3.0.0"
          - name: grunt-contrib-jshint
            version: "^2.1.0"
          - name: grunt-contrib-uglify
            version: "^4.0.1"
          - name: grunt-shell
            version: "~0.7.0"

    - role: configuration_files
      tags: config

    - role: rabbitmq
      tags: rabbitmq
      when: not development_environment

    - role: systemd_service
      tags: service

    - role: coopdevs.certbot_nginx
      become: yes
      vars:
        domain_name: "{{ domains | default([inventory_hostname]) | join(',') }}"
        letsencrypt_email: "{{ certificate_authority_email }}"
        certbot_nginx_cert_name: "{{ certbot_cert_name | default(inventory_hostname) }}"
        certbot_version: "0.28.0-1~deb9u2"
        certbot_nginx_version: "0.28.0-1~deb9u1"
      when: not development_environment
      tags: cert

    - role: needed_data
      become: yes
      tags: web
