---
- name:  Provision a machine to run Tryton server
  hosts: tryton
  roles:
    - role: users
      tags: users

    - role: tryton_configuration_files
      tags: config

    - role: geerlingguy.postgresql
      tags: database
      become: yes
      vars:
        postgresql_locales:
          '{{ db_locales }}'

    - role: postgres_configuration
      tags: database
      become: yes
