---
- name:  Provision a machine to run Tryton server
  hosts: tryton
  roles:
    - role: users
      tags: users

    - role: system_packages
      tags: system

    # This is a wrapper of Geerlingguy Postgresql role to allow create user and database without install PostgreSQL
    - role: postgres
      tags: database
      become: yes

    - role: virtualenv
      tags: virtualenv

    - role: geerlingguy.nodejs
      tags: npm
      become: yes
      vars:
        nodejs_version: "8.x"
        nodejs_install_npm_user: "{{ tryton_user }}"

    - role: tryton_configuration_files
      tags: config
